"""refactor: database

Revision ID: e2f2537fecff
Revises: 25bc7daf0f21
Create Date: 2024-08-20 23:29:40.854638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f2537fecff'
down_revision: Union[str, None] = '25bc7daf0f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('romancistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('id_romancista', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_romancista'], ['romancistas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.drop_table('books')
    op.drop_table('novelists')
    op.add_column('users', sa.Column('senha', sa.String(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'senha')
    op.create_table('novelists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('novelists_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='novelists_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('novelist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['novelist_id'], ['novelists.id'], name='books_novelist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    sa.UniqueConstraint('title', name='books_title_key')
    )
    op.drop_table('livros')
    op.drop_table('romancistas')
    # ### end Alembic commands ###
